### ISSUE TITLE
setttings not working 

### ISSUE THREAD

**Issue by Flyingtoast** [Fiddlekins/SpookyX#1]
The settings button seems to do nothing(at least in Opera).

**Comment by Fiddlekins** [comment]
Thanks, the issue is caused by a function provided by the userscript extension (which I use to grab the script version so that I don't have to update the settings menu manually each version).

Unfortunately it seems that the Violentmonkey extension doesn't support this, since it's a less developed derivative of the original Firefox based Greasemonkey addon.

I've done a quick investigation and found an alternate Opera extension, [Tampermonkey Beta](https://addons.opera.com/en-gb/extensions/details/tampermonkey-beta/?hidemessage=1), which DOES support this function. I've tested it to the extent that I've verified the settings menu doesn't cause the script to fail, currently too busy to check if the rest of the script works.

Let me know how you fare with it.
