### ISSUE TITLE
Not fetching full size images on hover.. 

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [Fiddlekins/SpookyX#21]
When i hover over the images, the image that follows the cursor is the same size as the thumbnail. Am i doing something wrong? 
(settings=default)

**Comment by Fiddlekins** [comment]
This is expected behaviour for when the thumbnail can be loaded but the fullsize version can't. It's not uncommon for the archives to be missing fullsize versions entirely alas.

**Comment by Vulgaris-Viridis** [comment]
This is rather unfortunate, because that was the #1 reason I've installed this extension. Well, other "functions" are still useful so at least there's that.. Thanks for the explanation.

**Comment by Fiddlekins** [comment]
To be clear, this should only be happening when the fullsize image is missing from the archive. With or without the extension running, you should be able to use the archive site's link that opens the image/video in fullsize and find the site returning a 404 error.

If the extension is failing to display a fullsize view of the image but you can use the link to access the fullsize version then please point me to an example because that's then a bug with the extension.

**Comment by Vulgaris-Viridis** [comment]
> If the extension is failing to display a fullsize view of the image but you can use the link to access the fullsize version then please point me to an example because that's then a bug with the extension.

That was the case actually, unfortunately i don't remember exactly on what pages the bug occurred but it did occur on multiple pages. I've just checked few pages and the extension works just fine.  If i run into it again i will open a new issue here. Thanks once again.
